version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest # Ensure this matches the version of Node.js you're using
    commands:
      - echo "Installing express"
      - npm install express # Install express directly without using package.json

  build:
    commands:
      - echo "Building the project"
      - mkdir -p build # Create a directory for the build output
      - cp -r ./* build/ # Copy all files into the build directory (including app.js, index.html, css, images, etc.)
      - cd build
      - zip -r ../app.zip . # Create the zip file of the build directory

  post_build:
    commands:
      - echo "Build completed. The app.zip file is ready for deployment."

artifacts:
  files:
    - app.zip # This is the file that AWS CodePipeline will deploy to Beanstalk
